name: "Sphinx: Render docs"

on: 
    push:
    workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Setup Pages
      uses: actions/configure-pages@v5
#    - name: Build HTML
#      uses: ammaraskar/sphinx-action@master
#      with:
#        docs-folder: ""
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Build
      run: |
        pip install --upgrade pip
        pip install -r ./requirements.txt
        pip install sphinx==8.2.3
        sphinx-build -M html "source" "build" --keep-going --no-color -w "/tmp/sphinx-log" 
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
        